000.5 Marvel Master Reading Order Pt 1 (1961-1972).cbl
003.5 Marvel Master Reading Order Pt 2 (1972-1981).cbl
004.5 Marvel Master Reading Order Pt 2 (1972-1981).cbl
005.5 Marvel Master Reading Order Pt 2 (1972-1981).cbl
009.5 Marvel Master Reading Order Pt 3 (1980-1987)..cbl
012.5 Marvel Master Reading Order Pt 3 (1980-1987).cbl
013.5 Marvel Master Reading Order Pt 3 (1980-1987).cbl
014.4 Marvel Master Reading Order Pt 3 (1980-1987).cbl

The smaller events are in both the master reading order and the event CBL files.  I didn't slices out the smaller events because they were not straightforward chronological order.

Added Part 1, 2 and 3

---

Marvel/Characters/Micronauts/The Micronauts.cbl
Marvel/Characters/Micronauts/The Micronauts.cbl.smartlist

Removed smart list and converted to standard <book> cbl.

Smart lists are dumb

---

README.md

Added several links to websites which host reading lists.

Added Web Resource Links to Readme

---

Marvel/Master Reading Order/Marvel Guides/2018-2021 Fresh Start/Part 15 Reign of X/[Marvel] 2018-2021 Part 15.4 Trial by Fire (MG).cbl

There is no 2020 volume, these are part of the ongoing 2019 volume.

Marvel Guides: correct Volume of X-Force books in Part 15.4

---

Marvel/Master Reading Order/CMRO/Core/[Marvel] CMRO Core Reading Order-Part 24.cbl
Marvel/Master Reading Order/CMRO/Core/[Marvel] CMRO Core Reading Order-Part 25.cbl
Marvel/Master Reading Order/CMRO/Expanded/[Marvel] CMRO Expanded Reading Order-Part 39.cbl
Marvel/Master Reading Order/CMRO/Main/[Marvel] CMRO Main Reading Order-Part 29.cbl
Marvel/Master Reading Order/Marvel Guides/1970-1984 Bronze Age/Part 1 Darker Territory/[Marvel] 1970-1984 Part 1.3 Monsters Unleashed (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 1 Once and Future/[Marvel] 2021-2023 Part 1.2 Heroes of the People (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 2 Destiny of X/[Marvel] 2021-2023 Part 2.2 Secret Pasts, Sinister Futures (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 2 Destiny of X/[Marvel] 2021-2023 Part 2.3 Hellfire and Brimstone (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 3 A.X.E. Judgement Day/[Marvel] 2021-2023 Part 3.2 Rush to Judgement (MG).cbl

Replaced Adventures into Fear with Frankenstein. closes #56 
Changed Amazing Spider-Man (2022) to The Amazing Spider-Man (2022), closes #55

Fix 1970-1984 Part 1.3 and Amazing Spider-Man (2022)

---

Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 6 Reconstruction/[Marvel] 2004-2012 Part 6.3 Endangered Species (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 8 Divided and Conquered/[Marvel] 2004-2012 Part 8.4 Divided We Stand (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2012-2015 Marvel NOW!/Part 1 Now or Never/[Marvel] 2012-2015 Part 1.1 Unity - Division (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2012-2015 Marvel NOW!/Part 17 Secret Wars/[Marvel] 2012-2015 Part 17.8 Everything Dies (MG).cbl
Marvel/Master Reading Order/Marvel Guides/README.md

Updated lists that were added since I did the first batch per issue created. I believe this was the last piece to close #50 but need to confirm with @themadman0980

Marvel Guide July Update

---

Marvel/Master Reading Order/Marvel Guides/2012-2015 Marvel NOW!/Part 5 Inhumanity/[Marvel] 2012-2015 Part 5.1 Mist Marvels (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2012-2015 Marvel NOW!/Part 5 Inhumanity/[Marvel] 2012-2015 Part 5.2 Rise of the Inhumans (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 4 Dark Web/[Marvel] 2021-2023 Part 4.1 End of the Spider-Verse (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 4 Dark Web/[Marvel] 2021-2023 Part 4.2 Spinning the Dark Web (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 4 Dark Web/[Marvel] 2021-2023 Part 4.3 Enter the Dark Web (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 4 Dark Web/[Marvel] 2021-2023 Part 4.4 Dark Web Aftermath (MG).cbl
Marvel/Master Reading Order/Marvel Guides/README.md

Created lists from the recent updates to the Marvel Guides site.

Added Dark Web and Inhumanity

---

Marvel/Master Reading Order/CBRO/[Marvel] Marvel Master Reading Order Part #12 (WEB-CBRO).cbl
Marvel/Master Reading Order/CMRO/Core/[Marvel] CMRO Core Reading Order-Part 24.cbl
Marvel/Master Reading Order/CMRO/Core/[Marvel] CMRO Core Reading Order-Part 25.cbl
Marvel/Master Reading Order/CMRO/Expanded/[Marvel] CMRO Expanded Reading Order-Part 38.cbl
Marvel/Master Reading Order/CMRO/Expanded/[Marvel] CMRO Expanded Reading Order-Part 39.cbl
Marvel/Master Reading Order/CMRO/Main/[Marvel] CMRO Main Reading Order-Part 29.cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 1 Once and Future/[Marvel] 2021-2023 Part 1.4 Banner of War (MG).cbl

Closes #58 
I know we said we would hold off, but I already had this started, so I thought I would wrap it up and we can decide what we want to do based on the cv situ.

Fixes Hulk volume year per comic vine

---

Other/unsorted/Fables.cbl

Fixes missing Fables Issues

---

DC/Events/unsorted/2023 - Knight Terrors.cbl

source: https://leagueofcomicgeeks.com/comics/event/14215/knight-terrors
Third time is the charm ... right ?

ADDED: 2023 - Knight Terrors.cbl

---

.gitignore
Other/unsorted/Dark Horse/Hellboy (Mignolaverse) TPB Reading Order.cbl

THE_LEGEND — 09/08/2023 8:20 AM
Made it using comicrack as it is the only software I know of to easily create cbl please recommend another if there is one , also almost all entries are TPB editions as almost every TPB contains additional as compared to the single issue as mentioned here https://comicbookreadingorders.com/other/hellboy-mignolaverse-reading-order/, the exception to this is "Hellboy and BPRD 1957" as there is no TPB yet. I directly followed http://www.multiversitycomics.com/annotations/hellboy-reading-order-2022/ instead of cbro version cause it is way outdated also has a text version https://docs.google.com/spreadsheets/d/1-O8Zw_v_F1-M1RZ4I3uN7AMTuTtK_1Ox4FkugzP-x8s/edit#gid=577555604

Hellboy TPB reading list

---

DC/Events/CBRO/1938-1986 - Part 1/[DC Comics] Jack Kirby's Fourth World (WEB-CBRO).cbl
DC/Events/CBRO/1938-1986 - Part 1/[DC Comics] Zatanna's Search (WEB-CBRO).cbl
DC/Events/CBRO/1997-2002 - Part 4/[DC Comics] Batman- No Man's Land (WEB-CBRO).cbl
DC/Events/CBRO/1997-2002 - Part 4/[DC Comics] Joker's Last Laugh (WEB-CBRO).cbl
DC/Events/CBRO/2005-2009 - Part 6/[DC Comics] Grant Morrison's Batman (WEB-CBRO).cbl
DC/Events/CBRO/2005-2009 - Part 6/[DC Comics] The Resurrection of Ra's al Ghul (WEB-CBRO).cbl
DC/Events/CBRO/2011-2015 - New 52/[DC Comics] Superman- H'el on Earth (WEB-CBRO).cbl
Marvel/Events/CBRO/[Marvel] Avengers & X-Men - AXIS (WEB-CBRO).cbl
Marvel/Events/CBRO/[Marvel] Child's Play (WEB-CBRO).cbl
Marvel/Events/CBRO/[Marvel] Dead Man's Hand (WEB-CBRO).cbl
Marvel/Events/CBRO/[Marvel] Jonathan Hickman's Marvel (WEB-CBRO).cbl
Marvel/Events/CBRO/[Marvel] Kraven's Last Hunt (WEB-CBRO).cbl
Marvel/Events/CBRO/[Marvel] X-Cutioner's Song (WEB-CBRO).cbl
Marvel/Events/unsorted/001 Reed Richards and Sue Storm's Wedding (1965).cbl
Marvel/Events/unsorted/015 Kraven's Last Hunt (1987).cbl
Marvel/Events/unsorted/029 X-Cutioner's Song (1992).cbl
Marvel/Master Reading Order/CBRO/[Marvel] Marvel Master Reading Order Part #06 (WEB-CBRO).cbl
Marvel/Master Reading Order/CMRO/Expanded/[Marvel] CMRO Expanded Reading Order-Part 10.cbl
Marvel/Master Reading Order/CMRO/Expanded/[Marvel] CMRO Expanded Reading Order-Part 15.cbl
Marvel/Master Reading Order/CMRO/Expanded/[Marvel] CMRO Expanded Reading Order-Part 17.cbl
Marvel/Master Reading Order/CMRO/Expanded/[Marvel] CMRO Expanded Reading Order-Part 39.cbl
Marvel/Master Reading Order/CMRO/Main/[Marvel] CMRO Main Reading Order-Part 09.cbl
Marvel/Master Reading Order/CMRO/Main/[Marvel] CMRO Main Reading Order-Part 29.cbl
Other/unsorted/Star Wars/CBRO/[Marvel] 005 Rise of the First Order.cbl

A variety of fixes, including:
- Apostrophe encoding fix
- Removal of " characters where it breaks the XML formatting
- Correction to Blade series match
- Corrected "Omega" issue number to match CV and Metron databases

Various list fixes

---

DC/Master Reading Order/Marvel Guides/2011-2016 New 52/Part 1 Point of Origin/[DC] 2011-2016 Part 1.1 In the Beginning….cbl
DC/Master Reading Order/Marvel Guides/2011-2016 New 52/Part 1 Point of Origin/[DC] 2011-2016 Part 1.2 Courting Disaster.cbl
DC/Master Reading Order/Marvel Guides/2011-2016 New 52/Part 1 Point of Origin/[DC] 2011-2016 Part 1.3 A League of Their Own.cbl
DC/Master Reading Order/Marvel Guides/2011-2016 New 52/Part 1 Point of Origin/[DC] 2011-2016 Part 1.4 The Culling.cbl
DC/Master Reading Order/Marvel Guides/2011-2016 New 52/Part 2 Edge of Darkness/[DC] 2011-2016 Part 2.1 Agents of the Dark.cbl
DC/Master Reading Order/Marvel Guides/2011-2016 New 52/Part 2 Edge of Darkness/[DC] 2011-2016 Part 2.2 Welcome to Rotworld.cbl
DC/Master Reading Order/Marvel Guides/2011-2016 New 52/Part 2 Edge of Darkness/[DC] 2011-2016 Part 2.3 A Wild Storm Approaches.cbl
DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 1 Lost Time/[DC] 2016-2021 Part 1.1 Restoring a Legacy.cbl
DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 1 Lost Time/[DC] 2016-2021 Part 1.2 Reign of the Supers.cbl
DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 1 Lost Time/[DC] 2016-2021 Part 1.3 Welcome to the Big Leagues.cbl
DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 1 Lost Time/[DC] 2016-2021 Part 1.4 Monsters of Gotham.cbl
DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 1 Lost Time/[DC] 2016-2021 Part 1.5 Generations.cbl
DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 2 Crossover Crisis/[DC] 2016-2021 Part 2.1 Justice League vs. Suicide Squad.cbl
DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 2 Crossover Crisis/[DC] 2016-2021 Part 2.2 The Lazarus Contract.cbl
DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 2 Crossover Crisis/[DC] 2016-2021 Part 2.3 Superman Reborn.cbl
DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 2 Crossover Crisis/[DC] 2016-2021 Part 2.4 The Button.cbl
Other/unsorted/Fables.cbl
Other/unsorted/Invincible.cbl
Other/unsorted/Spawn.cbl
Other/unsorted/Stephen King's The Dark Tower.cbl
Other/unsorted/The Boys.cbl
Other/unsorted/Valiant Universe.cbl
Other/unsorted/Watchmen.cbl

MarvelGuides.com (despite its URL) just introduced a couple of DC reading lists. Also I updated some of the other universes lists to include the CV IDs.

DC New 52 and Rebirth from MarvelGuides and others

---

Marvel/Teams/unsorted/Guardians of the Galaxy/Guardians of the Galaxy (2008) pt.1.cbl
Marvel/Teams/unsorted/Guardians of the Galaxy/Guardians of the Galaxy (2008) pt.2.cbl

Based on [https://comicbookreadingorders.com/marvel/characters/guardians-of-the-galaxy-reading-order/](https://comicbookreadingorders.com/marvel/characters/guardians-of-the-galaxy-reading-order/) including events

2008 Guardians of the Galaxy

---

Marvel/Events/CBRO/[Marvel] Ultimate Marvel (WEB-CBRO).cbl

Fixing the Duplicate Ultimate Avengers # 7-12 Issue (Github Issue #78)

Update [Marvel] Ultimate Marvel (WEB-CBRO).cbl

---

Marvel/Master Reading Order/CMRO/Main/[Marvel] CMRO Main Reading Order-Part 03.cbl

Fixing mis-identified issue for Captain America's Bicentennial Battles

Update [Marvel] CMRO Main Reading Order-Part 03.cbl

---

Marvel/Master Reading Order/CMRO/Misc/[Marvel] CMRO Ultimate Reading Order.cbl

Fixing Ultimate Iron Man mismatch and Ultimate Avengers Mismatches.

Update [Marvel] CMRO Ultimate Reading Order.cbl

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #06 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO/[Marvel] Marvel Master Reading Order Part #06 (WEB-CBRO).cbl
Marvel/Master Reading Order/CMRO/Core/[Marvel] CMRO Core Reading Order-Part 01.cbl

Closes #74  I think the best situation is to have one list with 994 issues instead of updating all the lists so they all have exactly 1000 books.  That would cause everyone to have to update all of their lists even though the content didn't change on all but the first list..

Removed duplicate issues

---

Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[1974-1983] X-Men Era Two The Uncanny X-Men (UXRO).cbl

Fixed missing classic x-men and mis-named X-Men series.

X-Men Era 2 Fixes

---

Marvel/Teams/X-Men/Age of Krakoa/[X-Men Krakoa 3.1] Fall of X.cbl

Changed to non-infinity comic version, and added latest issue that made it to cv.

Hellfire Gala Fix

---

Marvel/Master Reading Order/Marvel Guides/1970-1984 Bronze Age/Part 2 Death and Rebirth/[Marvel] 1970-1984 Part 2.1 Broken Hearts (MG).cbl
Marvel/Master Reading Order/Marvel Guides/1970-1984 Bronze Age/Part 2 Death and Rebirth/[Marvel] 1970-1984 Part 2.2 Avengers vs. Defenders (MG).cbl
Marvel/Master Reading Order/Marvel Guides/1970-1984 Bronze Age/Part 2 Death and Rebirth/[Marvel] 1970-1984 Part 2.3 The Terror From Titan (MG).cbl
Marvel/Master Reading Order/Marvel Guides/1970-1984 Bronze Age/Part 2 Death and Rebirth/[Marvel] 1970-1984 Part 2.4 Hellish Present, Darker Futures (MG).cbl
Marvel/Master Reading Order/Marvel Guides/1970-1984 Bronze Age/Part 2 Death and Rebirth/[Marvel] 1970-1984 Part 2.5 Giant-Size Changes (MG).cbl
Marvel/Master Reading Order/Marvel Guides/README.md

Added most recent updates to the Marvel Guides site: https://marvelguides.com/marvel-bronze-age-reading-order-part-2

Marvel Guide Bronze Age Updates

---

Marvel/Master Reading Order/Marvel Guides/2012-2015 Marvel NOW!/Part 6 All-New Marvel NOW!/[Marvel] 2012-2015 Part 6.1 Starting Point (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2012-2015 Marvel NOW!/Part 6 All-New Marvel NOW!/[Marvel] 2012-2015 Part 6.2 Hero Or Menace  (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2012-2015 Marvel NOW!/Part 6 All-New Marvel NOW!/[Marvel] 2012-2015 Part 6.3 Revolutionary War (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2012-2015 Marvel NOW!/Part 6 All-New Marvel NOW!/[Marvel] 2012-2015 Part 6.4 World Of Mutants (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2012-2015 Marvel NOW!/Part 6 All-New Marvel NOW!/[Marvel] 2012-2015 Part 6.5 World Of Avengers (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2012-2015 Marvel NOW!/Part 6 All-New Marvel NOW!/[Marvel] 2012-2015 Part 6.6 The Trial Of Jean Grey (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2015-2018 ANAD Marvel/Part 4 Avengers Standoff/[Marvel] 2015-2018 Part 4.4 Beyond the Standoff (MG).cbl
Marvel/Master Reading Order/Marvel Guides/README.md

Fix was the wrong match for a Free Comic Book Day issue.

Marvel Now update, and small fix for ANAD Part 4.4.

---

Marvel/Events/CBRO/2020-2022 - Part 12/[Marvel] Devil's Reign (WEB-CBRO).cbl

Update [Marvel] Devil's Reign (WEB-CBRO).cbl

---

Other/Star Wars/CBRO/[Marvel] 001 The High Republic.cbl
Other/Star Wars/CBRO/[Marvel] 002 The Clone Wars.cbl
Other/Star Wars/CBRO/[Marvel] 003 Reign of the Empire.cbl
Other/Star Wars/CBRO/[Marvel] 004-1 Age of Rebellion.cbl
Other/Star Wars/CBRO/[Marvel] 004-2 Vader Down.cbl
Other/Star Wars/CBRO/[Marvel] 004-3 Age of Rebellion.cbl
Other/Star Wars/CBRO/[Marvel] 004-4 The Screaming Citadel.cbl
Other/Star Wars/CBRO/[Marvel] 004-5 Age of Rebellion.cbl
Other/Star Wars/CBRO/[Marvel] 004-6 War of the Bounty Hunters.cbl
Other/Star Wars/CBRO/[Marvel] 004-7 Age of Rebellion.cbl
Other/Star Wars/CBRO/[Marvel] 005 Rise of the First Order.cbl

upated with the new comicvine data.  The original file had some extra information and the name was different than the filename.  Sicne I'm using my script that was changed as well.

Star Wars Fixes

---

Other/Star Wars/CBRO/[Marvel] 004-1 Age of Rebellion.cbl
Other/Star Wars/CBRO/[Marvel] 004-2 Vader Down.cbl
Other/Star Wars/CBRO/[Marvel] 004-3 Age of Rebellion.cbl
Other/unsorted/Star Wars/CBRO/[Marvel] 001 The High Republic.cbl
Other/unsorted/Star Wars/CBRO/[Marvel] 002 The Clone Wars.cbl
Other/unsorted/Star Wars/CBRO/[Marvel] 003 Reign of the Empire.cbl
Other/unsorted/Star Wars/CBRO/[Marvel] 004-1 Age of Rebellion.cbl
Other/unsorted/Star Wars/CBRO/[Marvel] 004-2 Vader Down.cbl
Other/unsorted/Star Wars/CBRO/[Marvel] 004-3 Age of Rebellion.cbl
Other/unsorted/Star Wars/CBRO/[Marvel] 004-4 The Screaming Citadel.cbl
Other/unsorted/Star Wars/CBRO/[Marvel] 004-5 Age of Rebellion.cbl
Other/unsorted/Star Wars/CBRO/[Marvel] 004-6 War of the Bounty Hunters.cbl
Other/unsorted/Star Wars/CBRO/[Marvel] 004-7 Age of Rebellion.cbl
Other/unsorted/Star Wars/CBRO/[Marvel] 005 Rise of the First Order.cbl

I updated the duplicate lists.  We should clean that up though, but I would like to leave that up to TheMadMan as he is the Star Wars guy

removed spanish language verison and also updated dupliacte lists.

---

Other/unsorted/Spawn.cbl

Rechecked CBRO and the Issue was supposed to be Blood and Shadows, which is actually named Spawn Annual per CV (and the indcia).

Fixed Spawn TPB issue

---

Marvel/Characters/Jessica Jones/[Marvel][2001-2020] Jessica Jones (CBRO).cbl
Other/American Vampire/[Vertigo][2010-2021] American Vampire (HTLC).cbl

adding two lists posted in the discord channel

Two user submitted lists.

---

DC/Characters/unsorted/Flash/Flash (CBRO).cbl

Based on https://comicbookreadingorders.com/dc/characters/the-flash-reading-order/

Flash (CBRO)

---

Marvel/Characters/Blade/Blade (CBRO).cbl

Based on https://comicbookreadingorders.com/marvel/characters/blade-reading-order/

Create Blade (CBRO).cbl

---

DC/Characters/unsorted/Constantine/Constantine (CBRO).cbl

Based on https://comicbookreadingorders.com/dc/characters/john-constantine-reading-order/

Constantine (CBRO)

---

Marvel/Master Reading Order/CMRO/Core/[Marvel] CMRO Core Reading Order-Part 20.cbl
Marvel/Master Reading Order/CMRO/Core/[Marvel] CMRO Core Reading Order-Part 21.cbl

CMRO fixes

---

DC/Characters/unsorted/Green Arrow/Green Arrow (CBRO).cbl

Based on https://comicbookreadingorders.com/dc/characters/green-arrow-reading-order/

Green Arrow (CBRO)

---

Marvel/Characters/The Punisher/The Punisher  (CBRO).cbl

Based on https://comicbookreadingorders.com/marvel/characters/punisher-reading-order/

Create The Punisher  (CBRO).cbl

---

Other/unsorted/BOOM! Power Rangers Simplified 1a.cbl
Other/unsorted/BOOM! Power Rangers Simplified 1b.cbl

Based on https://docs.google.com/spreadsheets/d/1QDtcbdxIcuZXfU6-m1vYxbo8c4jcXcDPzIobrEat9oQ/edit#gid=1075427689

BOOM! Power Rangers

---

DC/Characters/Batman/[DC] Batman - Golden Age [1939-1955].cbl
DC/Characters/Batman/[DC] Batman - New 52 [2010-2016].cbl
DC/Characters/Batman/[DC] Batman - Silver Age [1954-2004].cbl

batman golden age, silver age and New 52

---

DC/Events/CBRO/2021-2022+ - Infinite Frontier/[DC Comics] Lazarus Planet (WEB-CBRO).cbl
DC/Events/CBRO/README.md
DC/Master Reading Order/CBRO - With Events/README.md
DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order- Infinite Frontier (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/README.md
DC/Master Reading Order/CBRO/[DC Comics] DC Master Reading Order- Infinite Frontier (WEB-CBRO).cbl

Small update to Lazuras Planet event and added updates made to Infinite Frontier
(https://comicbookreadingorders.com/dc/infinite-frontier-reading-order/)

Infinite Frontier additions to get up to date with CBRO

---

Vertigo/Events/Fables/[Vertigo] [2009] The Great Fables Crossover (LoCG).cbl
Vertigo/Events/The Sandman Universe/[Vertigo] [1993-1994] The Children's Crusade (LoCG).cbl
Vertigo/Master Reading Order/Fables/[Vertigo] [2002-Present] Fables (CBRO).cbl

Added fables and removed old in unsorted. Added sandman event from LoCG.

Added vertigo lists

---

Image/Master Reading Order/Massive-Verse (Radiant Black)/[Image] [2014-2024] Massive-Verse (CBT).cbl

Per Comic Book Treasury
https://www.comicbooktreasury.com/massive-verse-comics/

Massive-Verse Addition

---

IDW/Characters/Transformers/[IDW] [2005-2017] Transformers (CBRO).cbl

I think I got something messed up with the other commits in motion.  this one should be cleaner.

Remove TPBs

---

Image/Characters/Spawn/[Image] [1992-Present] Spawn (CBRO).cbl

Updated to present CBRO listing versus original spawn cbl in unsorted folder.  Same version as before, I inadvertently deleted the branch this was part of.

Spawn CBRO

---

Marvel/Events/CBRO/2022-2023 - Part 13/[Marvel] A.X.E. Judgment Day (WEB-CBRO).cbl
Marvel/Events/CBRO/2022-2023 - Part 13/[Marvel] Dark Web (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #13 (WEB-CBRO).cbl

Had selected marvel UK release instead of Marvel US release for amazing spider-man, also identified a couple of mis identified issues as well.

Cbro marveluk fix

---

Image/Master Reading Order/Jupiter's Legacy/[Image] [2013-2024] Jupiter's Legacy.cbl
Marvel/Events/Official/[Marvel] (2018-11) Spider-Geddon (Official).cbl
Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order- A Fresh Start (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO/[Marvel] Marvel Master Reading Order- A Fresh Start (WEB-CBRO).cbl

Note that there is two series with same name and year on this list (Jupiter's Circle), so ID is essential for correct reading list matching (some intervention required in Komga).

Added Jupiter's Legacy

---

Marvel/Events/CBRO/1992-1999 - Part 5/[Marvel] Heroes Reborn (1996) (WEB-CBRO).cbl

found a list that didn't have cv ids in it somehow.

add cvids to Heroes Reborn list

---

DC/Characters/Batman/Batman - Modern Age/[DC] Batman Modern Age - Part 06 Legacy [1995-2014].cbl

Fixed Series naming for Batman/Judge Dredd "Die Laughing" to escape the inner quotes.

Fix un-escaped quote marks in [DC] Batman Modern Age - Part 06 Legacy [1995-2014].cbl

---

Other/unsorted/Friday the 13th Master List.cbl

There's no overarching story, but slasher fans are used to this and often we want everything seriously a part of any of the continuities of our franchises. So with that in mind, here's every Friday the 13th-specific book, only omissions for Jason's appearances in comics are the comedic ones in parody books. 
This is all in release order as again, no story to really follow but there's no real comprehensive list like this out there so I pieced it together from CV and my knowledge of this franchise (my first two movies ever watched were Happy Hooker Goes to Hollywood and Friday The 13th Part 3, one could say I destined to be this way) as a literal lifelong fan.

Friday the 13th Master List

---

Other/unsorted/Stephen King's The Dark Tower.cbl

Also added the End-World almanac.

Stephen King's DT - Removed all TPBs replaced with singles

---

Other/unsorted/A Nightmare on Elm Street.cbl
Other/unsorted/Chucky Master List.cbl

From Innovation's 3 series (including the special 3-D issue to mirror the final act in Freddy's Dead) to the very last Wildstorm issues with Krueger facing off against Ash and Jason twice. Sadly he's not been brought back in comic form (unless you count his many appearances in MAD since) so Krueger's comic journey ends in 2009.

Slasher movie Comic CBLs: Krueger/Chucky.

---

DC/Events/CBRO/2021-2022+ - Infinite Frontier/[DC Comics] Dark Crisis on Infinite Earths (WEB-CBRO).cbl

Wrong volume year from ComicVine

Update [DC Comics] Dark Crisis on Infinite Earths (WEB-CBRO).cbl

---

DC/Events/CBRO/2016-2021 - DC Rebirth/[DC Comics] Dark Nights- Death Metal (WEB-CBRO).cbl

Was pointing to the TPB rather than the correct issue

Update [DC Comics] Dark Nights- Death Metal (WEB-CBRO).cbl

---

DC/Characters/Batman/Batman - Modern Age/[DC] Batman Modern Age - Part 17 INTERLUDE Flashpoint [2009-2011].cbl

The name for this series on comic vine is [Flashpoint: The Legion of Doom](https://comicvine.gamespot.com/flashpoint-the-legion-of-doom/4050-40689/).

include full name for legion of doom series

---

DC/Characters/Batman/Batman - Modern Age/[DC] Batman Modern Age - Part 09 Bruce Wayne, Fugitive [1999-2006].cbl

One issue # error (mea culpa), one issue that has been pulled out of order becuase of the TPB source but does not make good sense in that place

Tweaks/Fixes while reading.

---

Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[2008-2009] X-Men Era Fifteen Manifest Destiny (UXRO).cbl

Missing first part of Messiah War added in place.

Fix to Ultimate X-Men Reading Order - Missing Issue

---

Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[2001-2004] X-Men Era Twelve New X-Men (UXRO).cbl

Should be The Origin series (Wolverine as a child, Dog, Rose, etc.).  Feel free to squash commits - had to do a second as clipboard screwed up my previous pastes.

Fix to UXRO era twelve - Wolverine opening volume

---

Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[2010-2011] X-Men Era Seventeen The X-Men Go Through Hell (UXRO).cbl

- Corrected Wolverine series to 2010 series (Wolverine in Hell storyline)
- Added second X-23 issue #1.  2010 had two series, a one-shot followed by a longer series.  Both are part of this reading list.

Fix X-23 and Wolverine series

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #08 (WEB-CBRO).cbl

Adjusted moon knight issues for Marvel CBRO with events

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #05 (WEB-CBRO).cbl

https://comicbookreadingorders.com/marvel/events/childs-play-reading-order/

Fixed x-force volume in Marvel CBRO with events part 5

---

Marvel/Events/LoCG/[2016-2017] Civil War II (Marvel Comics)(LoCG).cbl

Update on Series name, Issue and Series IDs. All data from ComicVine database.

Cbl list update1

---

Rebellion/Dark Judges Story Order/Dark Judges Story Order.cbl

Every Dark Judges story I could find both Dredd and Anderson related, in chronological order rather than publication.

Dark Judges

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #10 (WEB-CBRO).cbl

https://comicvine.gamespot.com/tomb-of-dracula-presents-throne-of-blood/4050-39883/

Fixed dracula series name in cbro events part 10

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #10 (WEB-CBRO).cbl

https://comicvine.gamespot.com/avengers-vs-x-men/4050-47331/
other series looks fine btw, only this one faulty

Fixed Avengers Vs. X-Men in cbro events part 10

---

Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[2013-2014] X-Men Era Nineteen The Broken Universe (UXRO).cbl
Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[2014-2015] X-Men Era Twenty Who Wants To Live Forever (UXRO).cbl
Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[2014-2015] X-Men Era Twenty-One Time Runs Out (UXRO).cbl
Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[2015-2017] X-Men Era Twenty-Two Terrigen Mists (UXRO).cbl

Fixes to New Avengers Volume (Vol1 -> Vol3)

Update [2013-2014] X-Men Era Nineteen The Broken Universe (UXRO).cbl

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #04 (WEB-CBRO).cbl

Was going through adding this CBLs into my komga instance, it highlighted this issues as duplicates in CBL and I did my best removing it
I struggle to find original reading order in CBRO site so I "guessed" and make decision based on issues placement in list order

removed duplicates from marvel CBRO with events Part 4

---

Marvel/Characters/Spider-Man/CBRO/[Marvel] Spider-Man with events.cbl
Marvel/Characters/Spider-Man/CBRO/[Marvel] Spider-Man without events.cbl

My best attempt at Spider-Man reading order creation from CBRO
Got all match in Komga (can't verify in Kavita)

Added CBRO Spider-Man reading orders

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #10 (WEB-CBRO).cbl

https://comicbookreadingorders.com/marvel/events/shattered-heroes-reading-order/
https://comicbookreadingorders.com/marvel/events/avengers-vs-x-men-reading-order/
Removed duplicate entry
Changed TPB issue to normal one : https://comicvine.gamespot.com/point-one-1-behold-the-watcher-harbinger-the-myth-/4000-301659/

Fixed Point one in Marvel CBRO part 10

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #10 (WEB-CBRO).cbl

https://comicbookreadingorders.com/marvel/events/fear-itself-reading-order/

fixed fear itself in part 10 cbro events

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #10 (WEB-CBRO).cbl

adjusted Villians for hire 0.1 issue in cbro with events part 10

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] All-New, All Different Marvel- All-New, All-Different Marvel Part #1 (WEB-CBRO).cbl

https://comicbookreadingorders.com/marvel/all-new-all-different-marvel-reading-order-part-1/
https://comicbookreadingorders.com/marvel/events/civil-war-ii-reading-order/
Removed duplicate, should be already read at the start of event

Removed International Iron Man #4 duplicate from all new all different list with events

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #11 (WEB-CBRO).cbl

https://comicbookreadingorders.com/marvel/marvel-master-reading-order-part-11/
This is story from Marvel’s Voices 2020 - https://marvel.fandom.com/wiki/Marvel%27s_Voices_Vol_1_1
Confirmed in CBRO discord:

Removed non existent issue from CBRO master order with events 11

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #02 (WEB-CBRO).cbl

https://comicvine.gamespot.com/gotham-by-gaslight-an-alternative-history-of-the-b/4000-124252/

fixed Gotham by Gaslight

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #01 (WEB-CBRO).cbl

fixed Deadman
7 issues of 1985
4 issues of 1986 volumes

fixed Deadman

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] New 52 Reading Order- New Part #1 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO - With Events/[DC Comics] New 52 Reading Order- New Part #2 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO - With Events/[DC Comics] New 52 Reading Order- New Part #3 (WEB-CBRO).cbl

https://comicvine.gamespot.com/all-star-western/4050-43019/

DC new 52 part 1 fixed all star western

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #01 (WEB-CBRO).cbl

https://comicvine.gamespot.com/daredevil/4050-30836/

Fixed Golden Age Secret Files

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] New 52 Reading Order- New Part #3 (WEB-CBRO).cbl

https://comicvine.gamespot.com/divergence-fcbd-special-edition/4050-82860/

Fixed Green Lantern: The Lost Army in New 52 CBRO part 3

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #05 (WEB-CBRO).cbl

https://comicbookreadingorders.com/marvel/events/mc2-reading-order/

Fixed spider girl to vol 2 in CBRO marvel part 5

---

DC/Events/LoCG/[2024] Absolute Power (DC Comics)(LoCG).cbl

League of Comic Geeks Events
https://leagueofcomicgeeks.com/comics/event/14398/absolute-power

Add DC Event "Absolute Power" League of Comic Geeks reading order

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] New 52 Reading Order- New Part #3 (WEB-CBRO).cbl

https://comicvine.gamespot.com/divergence-fcbd-special-edition/4050-81343/

Fixed Convergence Superman: Man of Steel in new 52 cbro part 3

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] All-New, All Different Marvel- All-New, All-Different Marvel Part #2 (WEB-CBRO).cbl

Present in main part, present in secret empire
Removed secret empire entry as duplicate

Removed Amazing Spider-Man Vol. 4 #25 due to it being present in main part

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #13 (WEB-CBRO).cbl

Fixed this
https://comicvine.gamespot.com/dark-web/4050-150051/
to this
https://comicvine.gamespot.com/dark-web/4050-146735/

Fixed CBRO Marvel part 13 Dark web from TPB to issue

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #10 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel NOW!- Marvel NOW! Part #2 (WEB-CBRO).cbl

Here we have this
https://comicbookreadingorders.com/marvel/marvel-now-reading-order-part-2/
Which is that:
https://comicvine.gamespot.com/uncanny-avengers/4050-79736/
Not this:
https://comicvine.gamespot.com/uncanny-avengers/4050-85318/

Adjusted Uncanny Avengers vol 2

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #12 (WEB-CBRO).cbl

https://comicbookreadingorders.com/marvel/events/devils-reign-reading-order/

Fixed CBRo Marvel part 12 daredevil

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] All-New, All Different Marvel- All-New, All-Different Marvel Part #2 (WEB-CBRO).cbl

Adjusted to actual vol 2
https://comicvine.gamespot.com/monsters-unleashed/4050-98067/
we have vol 3 somewhere in the list later
Difference in `!`

Adjusted Monster Unleashed vol 2 to actual vol 2

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #01 (WEB-CBRO).cbl

https://comicvine.gamespot.com/daredevil/4050-3033/

fixed The Legion of Super-Heroes

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] New 52 Reading Order- New Part #3 (WEB-CBRO).cbl

https://comicvine.gamespot.com/divergence-fcbd-special-edition/4050-79691/

Fixed The Multiversity: Guidebook in new 52 cbro part 3

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #10 (WEB-CBRO).cbl

Sure this was meant to be inside avengers vs xmen arc https://comicvine.gamespot.com/uncanny-x-men/4050-43785/
not vol 3
https://comicvine.gamespot.com/uncanny-x-men/4050-57181/

Adjusted Uncanny X-Men volume in avengers vs xmen cbro with events part 10

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] New 52 Reading Order- New Part #3 (WEB-CBRO).cbl

https://comicvine.gamespot.com/divergence-fcbd-special-edition/4050-89370/

Fixed Justice League Darkseid War Special in new 52 CBRO part 3

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #01 (WEB-CBRO).cbl

https://comicvine.gamespot.com/legends-of-the-dcu-crisis-on-infinite-earths/4050-25595/

fixed Legends of the DCU: Crisis on Infinite Earths

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #13 (WEB-CBRO).cbl

First one is good, other ones are not, fixed

Fixed CBRO Marvel part 13 "The Avengers: War Across Time"

---

Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[2018-2019] X-Men Era Twenty-Four Disassembled (UXRO).cbl

Vol 4 featured in previous list, and this volume aligns with the ending in Winter's End.

Correcting Iceman to Vol 5

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #13 (WEB-CBRO).cbl

https://comicvine.gamespot.com/captain-america-sentinel-of-liberty/4050-143632/

Fixed CBRO Marvel part 13 Captain America: Sentinel of Liberty fixed to correct series year

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #05 (WEB-CBRO).cbl

Removed issues which intersects inside various events.

Removed duplicates from Marvel CBRO with Events part 5

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #07 (WEB-CBRO).cbl

Removed duplicates from Marvel CBRO with Events part 7
They are present earlier

Removed duplicates from Marvel CBRO with Events part 7

---

Marvel/Teams/X-Men/Ultimate X-Men Reading Order/README.md
Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[2019-2021] X-Men Era Twenty-Five Dawn of X (UXRO).cbl
Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[2021-2022] X-Men Era Twenty-Six Reign of X (UXRO).cbl
Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[2022-2023] X-Men Era Twenty-Seven Destiny of X (UXRO).cbl
Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[2023-2024] X-Men Era Twenty-Eight Fall of X (UXRO).cbl

Fixes to existing partial lists on Age of Krakoa, and addition of the final lists (after which UXRO has posted there will not be updates for a while).
Hold fire on a merge for now - one more Era to create but will do so in the morning once I have coffee and a refreshed CV api limit.

Ultimate X-Men Reading Order - Age of Krakoa Fixes/Completion

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #04 (WEB-CBRO).cbl

part of Batman: No Man's Land event and Day of Judgment event

fix Batman: Day of Judgment duplicate in DC #4

---

Marvel/Teams/X-Men/Age of Krakoa/Age of Krakoa - Eras Lists/[X-Men Krakoa 3.1] Fall of X.cbl
Marvel/Teams/X-Men/Age of Krakoa/Age of Krakoa - Single List/[X-Men Krakoa] [2019-Present] The Age of Krakoa.cbl

Should round off with the final issue in the Immortal X-Men series.

Incorrect issue at end of FoX

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #03 (WEB-CBRO).cbl

https://comicvine.gamespot.com/demon-annual/4050-18553/

Fixed The Demon Annual

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #02 (WEB-CBRO).cbl

https://comicvine.gamespot.com/books-of-magic/4050-4354/

fixed Books of Magic

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #02 (WEB-CBRO).cbl

https://comicvine.gamespot.com/firestorm-the-nuclear-man/4050-3789/
https://comicvine.gamespot.com/firestorm/4050-149680/
Comicvine is a mess :(

fixed Firestorm

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #02 (WEB-CBRO).cbl

https://comicvine.gamespot.com/arkham-asylum/4050-128951/
https://en.wikipedia.org/wiki/Arkham_Asylum:_A_Serious_House_on_Serious_Earth

fixed Arkham Asylum

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #02 (WEB-CBRO).cbl

https://comicvine.gamespot.com/batman-the-cult/4050-3979/

fixed Batman: The Cult

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #02 (WEB-CBRO).cbl

https://comicvine.gamespot.com/batman-dark-knight-dark-city/4050-4720/

fixed Legends of the Dark Knight

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #03 (WEB-CBRO).cbl

Incorrect issue was put in between 1993 issues

fixed Robin 1993

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #03 (WEB-CBRO).cbl

https://comicvine.gamespot.com/demon-annual/4050-20558/

fixed Batman Adventures: Mad love

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #03 (WEB-CBRO).cbl

https://comicvine.gamespot.com/demon-annual/4050-18997/

fixed Black Canary/Oracle: Birds of Prey

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #03 (WEB-CBRO).cbl

https://comicvine.gamespot.com/demon-annual/4050-4954/

fixed Bloodbath

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #03 (WEB-CBRO).cbl

https://comicvine.gamespot.com/demon-annual/4050-5515/

fixed The Power of Shazam!

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #03 (WEB-CBRO).cbl

There is two 0 issues, fixed first one to 4, because they go backwards

fixed Zero Hour: Crisis in Time

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #03 (WEB-CBRO).cbl

Present in multiple events, removed later entry

fixed Showcase 94 duplicate

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #03 (WEB-CBRO).cbl

Present in other event, removed later entries

Fixed superman duplicates

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #13 (WEB-CBRO).cbl

https://comicvine.gamespot.com/sins-of-sinister/4050-147646/

fixed Sins of Sinister HC to issue

---

Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[2018-2019] X-Men Era Twenty-Four Disassembled (UXRO).cbl

More missing Alpha/Omega bookend issues for events.

Added missing Alpha/Omega issues to Era 24 list

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #04 (WEB-CBRO).cbl

https://comicvine.gamespot.com/_/4000-153815/

fix Batman: Spoiler/Huntress-Blunt Trauma in DC #4

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #04 (WEB-CBRO).cbl

https://comicvine.gamespot.com/_/4000-190562/

fix New Gods Secret Files in DC #4

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #04 (WEB-CBRO).cbl

https://comicvine.gamespot.com/_/4000-73301/

fix The Trenchcoat Brigade in DC #4

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #04 (WEB-CBRO).cbl

https://comicvine.gamespot.com/_/4000-78194/
part of last laugh event

fix Harley Quinn in DC #4

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #04 (WEB-CBRO).cbl

https://comicvine.gamespot.com/_/4000-78349/

fix JLA Secret Files in DC #4

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #04 (WEB-CBRO).cbl

https://comicvine.gamespot.com/_/4000-124220/

fix Superboy and The Ravers in DC #4

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #04 (WEB-CBRO).cbl

https://comicvine.gamespot.com/_/4000-149831/

fix Starman: The Mist in DC #4

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #04 (WEB-CBRO).cbl

https://comicvine.gamespot.com/_/4000-131873/

fix Young Justice in No Man's Land in DC #4

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #04 (WEB-CBRO).cbl

https://comicvine.gamespot.com/_/4000-150024/

fix Batman/Scarface: A Psychodrama in DC #4

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #04 (WEB-CBRO).cbl

https://comicvine.gamespot.com/_/4000-157428/

fix Superman: Our Worlds at War Secret Files in DC #4

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #04 (WEB-CBRO).cbl

https://comicvine.gamespot.com/_/4000-189894/

fix Flash: Our Worlds at War in DC #4

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #04 (WEB-CBRO).cbl

part of genesis event and main reading order
removed later entry

fix The Power of SHAZAM duplicate, part of genesis event in DC #4

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #04 (WEB-CBRO).cbl

part of Batman: No Man's Land event and Day of Judgment events

fix Azrael: Agent of the Bat  duplicate in DC #4

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #10 (WEB-CBRO).cbl

due to availability issues changed printed issues to infinite thingy 
https://comicvine.gamespot.com/xmen-92-infinite-comic/4050-82272/

changed x-men '92 printed issues to infinite comics in part 10 cbro events

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #10 (WEB-CBRO).cbl

Due to availability issues
https://comicvine.gamespot.com/allnew-captain-america-fear-him-infinite-comic/4050-77871/

changed All-New Captain America: Fear Him printed issues to infinite comics in part 10 cbro events

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] All-New, All Different Marvel- All-New, All-Different Marvel Part #2 (WEB-CBRO).cbl

Updated to infinite comic
Same thing
But available

Changed slapstick to available one

---

Marvel/Teams/X-Men/Age of Krakoa/Age of Krakoa - Eras Lists/[X-Men Krakoa 3.2] Fall of the House of X.cbl
Marvel/Teams/X-Men/Age of Krakoa/Age of Krakoa - Single List/[X-Men Krakoa] [2019-Present] The Age of Krakoa.cbl
Marvel/Teams/X-Men/Age of Krakoa/README.md

Added the final Wolverine/X-Men issues to this list.  I've not heard back from the original source author, so it might be worth a complete review at some point as having read it it is ... oddly ordered.

Patched issues at end of FoHoX

---

Other/The Authority/README.md
Other/The Authority/The Authority 00 - Prior Reading [1995-1999].cbl
Other/The Authority/The Authority 01 - Full Reading Order[1999-2011].cbl

See the README for source.  I have split it into two lists in case people want to avoid jumping around bits of StormWatch for the hell of it / because they want to do a separate StormWatch read.

Reading list for The Authority

---

Valiant/Master Reading Order/[Valiant] [2012-2019] Valiant Universe (CBRO).cbl

Without the events, there are inexplicable jumps.

Expand Valiant CBRO master list to include embedded events

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #06 (WEB-CBRO).cbl

Fix to tales of the unexpected vol 2

Update [DC Comics] DC Master Reading Order Part #06 (WEB-CBRO).cbl

---

Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 08 Cosmic Chaos/[Marvel] 2021-2023 Part 8.1 Fractured Four (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 08 Cosmic Chaos/[Marvel] 2021-2023 Part 8.2 Grootfall (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 08 Cosmic Chaos/[Marvel] 2021-2023 Part 8.3 Might and Magic (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 08 Cosmic Chaos/[Marvel] 2021-2023 Part 8.4 Contest of Chaos (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 09 Fall of X/[Marvel] 2021-2023 Part 9.1 Before the Fall (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 09 Fall of X/[Marvel] 2021-2023 Part 9.2 Mutant Massacre (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 09 Fall of X/[Marvel] 2021-2023 Part 9.3 Scattered Mutants (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 09 Fall of X/[Marvel] 2021-2023 Part 9.4 Krakoa's Last Stand (MG).cbl

Added:
Part 08 Cosmic Chaos
Part 09 Fall of X

Marvel Guides: add Parts 8 and 9

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #14 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO/[Marvel] Marvel Master Reading Order Part #14 (WEB-CBRO).cbl

title covers I guess
https://comicbookreadingorders.com/marvel/marvel-master-reading-order-part-14/

Added CBRO Marvel part 14

---

DC/Characters/unsorted/Shazam!/Shazam! 002 - Post Crisis.cbl
DC/Characters/unsorted/Shazam!/Shazam! 003 - New52_Rebirth.cbl
DC/Characters/unsorted/Superboy/Superboy 001 - Pre-Crisis.cbl
DC/Characters/unsorted/Superboy/Superboy 002 - Pre-Crisis.cbl
DC/Characters/unsorted/Superboy/Superboy 003 - Conner Kent (Post-Crisis).cbl
DC/Characters/unsorted/Superboy/Superboy 004 - New52.cbl

No 2 part commit as this one was very clean so differences are obvious.

CV ID Mapping - DC/Characters/unsorted/Shazam_Superboy

---

DC/Characters/unsorted/Catwoman/Catwoman 001 - Pre-Crisis.cbl
DC/Characters/unsorted/Catwoman/Catwoman 002 - Post Crisis.cbl
DC/Characters/unsorted/Catwoman/Catwoman 003 - New 52_Rebirth.cbl
DC/Characters/unsorted/Constantine/Constantine 001.cbl
DC/Characters/unsorted/Constantine/Constantine 002 - New 52_Rebirth.cbl
DC/Characters/unsorted/Cyborg/Cyborg - New52_Rebirth.cbl
DC/Characters/unsorted/Deathstroke/Deathstroke 001.cbl
DC/Characters/unsorted/Deathstroke/Deathstroke 002 (New 52_Rebirth).cbl
DC/Characters/unsorted/Doom Patrol/Doom Patrol 1.cbl
DC/Characters/unsorted/Firestorm/Firestorm 001.cbl
DC/Characters/unsorted/Firestorm/Firestorm 002 - New52_Rebirth.cbl
DC/Characters/unsorted/Flash/Flash 001 - Jay Garrick Years.cbl
DC/Characters/unsorted/Flash/Flash 002 - Barry Allen Years.cbl
DC/Characters/unsorted/Flash/Flash 003 - Post Crisis Wally West.cbl
DC/Characters/unsorted/Flash/Flash 004 .cbl
DC/Characters/unsorted/Flash/Flash 005 - New52_Rebirth.cbl

CV ID Mapping - DC/Characters/unsorted/C to F
- Catwoman's Caper was some one-shot tiny book distributed with pop-tarts.  There is no CV entry for it.

CV ID Mapping - DC/Characters/unsorted/c-f

---

DC/Teams/unsorted/Justice League/Justice League 001 (Pre-Crisis).cbl
DC/Teams/unsorted/Justice League/Justice League 002 (Post Crisis).cbl
DC/Teams/unsorted/Justice League/Justice League 003 (Task Force).cbl
DC/Teams/unsorted/Justice League/Justice League 004 (JLA - 1996).cbl
DC/Teams/unsorted/Justice League/Justice League 005 (2006).cbl
DC/Teams/unsorted/Justice League/Justice League 006 (New 52).cbl
DC/Teams/unsorted/Justice League/Justice League 007 (Rebirth).cbl
DC/Teams/unsorted/Justice League/Justice League Mini-Series.cbl
DC/Teams/unsorted/Justice League/Justice League TPB 1 - SIlver Age_Pre-Crisis.cbl
DC/Teams/unsorted/Justice League/Justice League TPB 2 - Post Crisis.cbl
DC/Teams/unsorted/Justice League/Justice League TPB 3 - New52_Rebirth.cbl

- I have not touched the TPB lists as I can't find corresponding entries on CV for most of the items listed.
- In mini-series, expanded one TPB and reordered The Nail and Another Nail (as they stood out as out of order)

CV ID Mapping - DC/Teams/unsorted/Justice League

---

DC/Characters/unsorted/Aquaman/Aquaman 001 - Golden Age.cbl
DC/Characters/unsorted/Aquaman/Aquaman 002 - Silver_Bronze.cbl
DC/Characters/unsorted/Aquaman/Aquaman 003 - Post Crisis.cbl
DC/Characters/unsorted/Aquaman/Aquaman 004 - New 52_Rebirth.cbl
DC/Characters/unsorted/Azrael/Azrael.cbl

Two part commit to aide side by side diff alignment.
Some TPB expansion (where sensible/obvious).

CV ID Mapping - DC/Characters/unsorted/a

---

Other/unsorted/Dark Horse/Bacchus.cbl
Other/unsorted/Dark Horse/Concrete.cbl
Other/unsorted/Dynamite/Game of Thrones.cbl
Other/unsorted/Dynamite/Vampirella.cbl

Adding CV mappings for lists missing entries in Other

CV ID Mapping - Other

---

DC/Characters/Green Lantern/CBT/Green Lantern [2023-2024] Dawn of DC (CBT).cbl
DC/Characters/Green Lantern/CBT/README.md
DC/Characters/Green Lantern/Reddit/Green Lantern 01 - Silver Age.cbl
DC/Characters/Green Lantern/Reddit/Green Lantern 02 - Bronze Age.cbl
DC/Characters/Green Lantern/Reddit/Green Lantern 03 - Copper Age.cbl
DC/Characters/Green Lantern/Reddit/Green Lantern 04 - Kyle Rayner Era.cbl
DC/Characters/Green Lantern/Reddit/Green Lantern 05 - Geoff Johns Era.cbl
DC/Characters/Green Lantern/Reddit/Green Lantern 06 - New 52.cbl
DC/Characters/Green Lantern/Reddit/Green Lantern 07 - DC Rebirth.cbl
DC/Characters/Green Lantern/Reddit/Green Lantern 08 - Infinite Frontier.cbl
DC/Characters/Green Lantern/Reddit/Green Lantern XX - Non-Canon.cbl
DC/Characters/Green Lantern/Reddit/README.md

3 additional list to follow after a few hours of CV API calls.

Green Lantern: Kyle Rayner to Dawn of DC

---

Marvel/Master Reading Order/CBRO/[Marvel] Marvel Master Reading Order Part #13 (WEB-CBRO).cbl
Marvel/Master Reading Order/CMRO/Core/[Marvel] CMRO Core Reading Order-Part 03.cbl
Marvel/Master Reading Order/CMRO/Core/[Marvel] CMRO Core Reading Order-Part 12.cbl
Marvel/Master Reading Order/CMRO/Core/[Marvel] CMRO Core Reading Order-Part 24.cbl
Marvel/Master Reading Order/CMRO/Essential/[Marvel] CMRO Essential Reading Order-Part 03.cbl
Marvel/Master Reading Order/CMRO/Expanded/[Marvel] CMRO Expanded Reading Order-Part 10.cbl
Marvel/Master Reading Order/CMRO/Expanded/[Marvel] CMRO Expanded Reading Order-Part 15.cbl
Marvel/Master Reading Order/CMRO/Expanded/[Marvel] CMRO Expanded Reading Order-Part 17.cbl
Marvel/Master Reading Order/CMRO/Expanded/[Marvel] CMRO Expanded Reading Order-Part 20.cbl
Marvel/Master Reading Order/CMRO/Expanded/[Marvel] CMRO Expanded Reading Order-Part 22.cbl
Marvel/Master Reading Order/CMRO/Expanded/[Marvel] CMRO Expanded Reading Order-Part 23.cbl
Marvel/Master Reading Order/CMRO/Expanded/[Marvel] CMRO Expanded Reading Order-Part 39.cbl
Marvel/Master Reading Order/CMRO/Main/[Marvel] CMRO Main Reading Order-Part 09.cbl
Marvel/Master Reading Order/CMRO/Main/[Marvel] CMRO Main Reading Order-Part 13.cbl
Marvel/Master Reading Order/CMRO/Main/[Marvel] CMRO Main Reading Order-Part 14.cbl
Marvel/Master Reading Order/CMRO/Main/[Marvel] CMRO Main Reading Order-Part 29.cbl
Marvel/Master Reading Order/CMRO/Misc/[Marvel] CMRO Golden Reading Order.cbl
Marvel/Master Reading Order/Marvel Guides/1939-1956 Golden Age/Part 02 Super Soldiers/[Marvel] 1939-1956 Part 2.3 Winners Unite! (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2012-2015 Marvel NOW!/Part 16 Time Runs Out/[Marvel] 2012-2015 Part 16.1 Ultimate Interlude (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2018-2021 Fresh Start/Part 16 Fresh Restart/[Marvel] 2018-2021 Part 16.1 Reborn Again (MG).cbl

Only including changes that include material (string) changes, or those that needed fixing because of non-escaped quote marks in the titltes.

CVNameReview - /Marvel/Master Reading Order

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #03 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #06 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #07 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #08 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order- Infinite Frontier (WEB-CBRO).cbl
DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Rebirth- DC Rebirth Part #1 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Rebirth- DC Rebirth Part #2 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO - With Events/[DC Comics] DC You (WEB-CBRO).cbl
DC/Master Reading Order/CBRO - With Events/[DC Comics] New 52 Reading Order- New Part #3 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] DC Master Reading Order Part #01 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] DC Master Reading Order Part #02 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] DC Master Reading Order Part #03 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] DC Master Reading Order Part #04 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] DC Master Reading Order Part #06 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] DC Master Reading Order Part #07 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] DC Master Reading Order Part #08 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] DC Master Reading Order- Infinite Frontier (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] DC Rebirth- DC Rebirth Part #1 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] DC Rebirth- DC Rebirth Part #2 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] DC You (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] New 52 Reading Order- New Part #1 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] New 52 Reading Order- New Part #2 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] New 52 Reading Order- New Part #3 (WEB-CBRO).cbl
DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 1 Lost Time/[DC] 2016-2021 Part 1.1 Restoring a Legacy.cbl
DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 1 Lost Time/[DC] 2016-2021 Part 1.3 Welcome to the Big Leagues.cbl
DC/Master Reading Order/Marvel Guides/2016-2021 Rebirth/Part 2 Crossover Crisis/[DC] 2016-2021 Part 2.1 Justice League vs. Suicide Squad.cbl

In addition to the name review, one list had an incorrect volume linked.  Have corrected the IDs (was linked to a re-release, should have been the original).  Split commits to differentiate changes.

CVNameReview - /DC/Master Reading Order

---

DC/Events/LoCG/[1994] Zero Hour (DC Comics)(LoCG).cbl
DC/Events/LoCG/[1998-1999] No Man's Land (DC Comics)(LoCG).cbl
DC/Events/LoCG/[1998] Cataclysm (DC Comics)(LoCG).cbl
DC/Events/LoCG/[2005-2006] Infinite Crisis (DC Comics)(LoCG).cbl
DC/Events/LoCG/[2008-2009] Final Crisis (DC Comics)(LoCG).cbl
DC/Events/LoCG/[2008-2010] Blackest Night (DC Comics)(LoCG).cbl
DC/Events/LoCG/[2010-2011] Flashpoint (DC Comics)(LoCG).cbl
DC/Events/LoCG/[2012] Night of the Owls (DC Comics)(LoCG).cbl
DC/Events/LoCG/[2015-2016] Justice League Darkseid War (DC Comics)(LoCG).cbl
DC/Events/LoCG/[2015] Convergence (DC Comics)(LoCG).cbl
DC/Events/LoCG/[2017-2018] Dark Nights Metal (DC Comics)(LoCG).cbl

CVNameReview - /DC/Events/LoCG

---

DC/Events/CBRO/1938-1986 - Part 1/[DC Comics] Crisis on Infinite Earths (WEB-CBRO).cbl
DC/Events/CBRO/1991-1997 - Part 3/[DC Comics] Bloodlines (WEB-CBRO).cbl
DC/Events/CBRO/1991-1997 - Part 3/[DC Comics] DC Universe- Trinity (WEB-CBRO).cbl
DC/Events/CBRO/1991-1997 - Part 3/[DC Comics] Eclipso- The Darkness Within (WEB-CBRO).cbl
DC/Events/CBRO/1991-1997 - Part 3/[DC Comics] Final Night (WEB-CBRO).cbl
DC/Events/CBRO/1991-1997 - Part 3/[DC Comics] Zero Hour (WEB-CBRO).cbl
DC/Events/CBRO/1997-2002 - Part 4/[DC Comics] Batman- Cataclysm (WEB-CBRO).cbl
DC/Events/CBRO/1997-2002 - Part 4/[DC Comics] Batman- No Man's Land (WEB-CBRO).cbl
DC/Events/CBRO/1997-2002 - Part 4/[DC Comics] Genesis (WEB-CBRO).cbl
DC/Events/CBRO/1997-2002 - Part 4/[DC Comics] Our Worlds at War (WEB-CBRO).cbl
DC/Events/CBRO/2005-2009 - Part 6/[DC Comics] Countdown to Infinite Crisis (WEB-CBRO).cbl
DC/Events/CBRO/2005-2009 - Part 6/[DC Comics] Grant Morrison's Batman (WEB-CBRO).cbl
DC/Events/CBRO/2005-2009 - Part 6/[DC Comics] Infinite Crisis (WEB-CBRO).cbl
DC/Events/CBRO/2008-2011 - Part 7/[DC Comics] Battle for the Cowl (WEB-CBRO).cbl
DC/Events/CBRO/2008-2011 - Part 7/[DC Comics] Blackest Night (WEB-CBRO).cbl
DC/Events/CBRO/2008-2011 - Part 7/[DC Comics] Final Crisis (WEB-CBRO).cbl
DC/Events/CBRO/2008-2011 - Part 7/[DC Comics] Flashpoint (WEB-CBRO).cbl
DC/Events/CBRO/2011-2015 - New 52/[DC Comics] Convergence (WEB-CBRO).cbl
DC/Events/CBRO/2011-2015 - New 52/[DC Comics] Multiversity (WEB-CBRO).cbl
DC/Events/CBRO/2011-2015 - New 52/[DC Comics] The Black Diamond Probability (WEB-CBRO).cbl
DC/Events/CBRO/2015-2016 - DC You/[DC Comics] Darkseid War (WEB-CBRO).cbl
DC/Events/CBRO/2016-2021 - DC Rebirth/[DC Comics] Dark Nights- Death Metal (WEB-CBRO).cbl
DC/Events/CBRO/2016-2021 - DC Rebirth/[DC Comics] Dark Nights- Metal (WEB-CBRO).cbl

CVNameReview - /DC/Events/CBRO

---

DC/Creator Runs/[DC] [1993-2005] Batman by Loeb and Sale.cbl
DC/Creator Runs/[DC] [1999-2009] JSA by Geoff Johns.cbl
DC/Creator Runs/[DC] [2000-2011] Flash by Geoff Johns.cbl

CVNameReview - /DC/Creator Runs

---

DC/Characters/unsorted/Constantine/Constantine (CBRO).cbl
DC/Characters/unsorted/Flash/Flash (CBRO).cbl
DC/Characters/unsorted/Green Arrow/Green Arrow (CBRO).cbl

Most of this folder don't have CV ids in them so no checks done.  That's a whole different pass to do later.

CVNameReview: /DC/Characters/unsorted

---

DC/Characters/Batman/Batman - Modern Age/[DC] Batman Modern Age - Part 05 Knightfall [1991-2019].cbl
DC/Characters/Batman/Batman - Modern Age/[DC] Batman Modern Age - Part 06 Legacy [1995-2008].cbl
DC/Characters/Batman/Batman - Modern Age/[DC] Batman Modern Age - Part 08 New Gotham [2000-2016].cbl
DC/Characters/Batman/Batman - Modern Age/[DC] Batman Modern Age - Part 09 Bruce Wayne, Fugitive [1999-2006].cbl
DC/Characters/Batman/Batman - Modern Age/[DC] Batman Modern Age - Part 13 Countdown[2006-2011].cbl
DC/Characters/Batman/Batman - Modern Age/[DC] Batman Modern Age - Part 14 INTERLUDE Final Crisis [2005-2009].cbl
DC/Characters/Batman/Batman - Modern Age/[DC] Batman Modern Age - Part 15 Batman Reborn [1989-2012].cbl
DC/Characters/Batman/[DC] Batman - New 52 [2010-2016].cbl
DC/Characters/Batman/[DC] Batman - Post-Crisis  [1986-2011].cbl

Mostly small punctuation / typographic changes.  Wasn't expecting much to change in this folder given I did a review of Batman - Modern Age last October, but looks like one series changed name within weeks of me doing those updates!

CVNameReview: /DC/Characters/Batman

---

Marvel/Master Reading Order/CMRO/Expanded/[Marvel] CMRO Expanded Reading Order-Part 42.cbl
Marvel/Master Reading Order/CMRO/README.md

CMRO-Nov2024 Update

---

Marvel/Characters/Spider-Man/CBRO/[Marvel] Miles Morales (CBRO) no events.cbl

https://comicbookreadingorders.com/marvel/characters/miles-morales-reading-order/

Miles Morales CBRO no events

---

Marvel/Characters/Spider-Man/CBRO/Miles Morales (CBRO) with events.cbl

https://comicbookreadingorders.com/marvel/characters/miles-morales-reading-order/

[Marvel] Miles Morales (CBRO) with events

---

Marvel/Characters/Ms Marvel/[Marvel] Kamala Khan (CBRO) no events.cbl

https://comicbookreadingorders.com/marvel/characters/kamala-khan-reading-order/

Create [Marvel] Kamala Khan (CBRO) no events.cbl

---

Marvel/Characters/Ms Marvel/[Marvel] Kamala Khan (CBRO) with events.cbl

https://comicbookreadingorders.com/marvel/characters/kamala-khan-reading-order/

Create [Marvel] Kamala Khan (CBRO) with events.cbl

---

Marvel/Events/CBRO/2015-2018 - All-New All Different Marvel/[Marvel] Monsters Unleashed (WEB-CBRO).cbl

corrected series and issue cvid for monsters unleashed!

Update [Marvel] Monsters Unleashed (WEB-CBRO).cbl

---

Marvel/Events/CBRO/2015-2018 - All-New All Different Marvel/[Marvel] Civil War II (WEB-CBRO).cbl

Updated volume to match https://comicvine.gamespot.com/rocket-raccoon-and-groot/4050-86989/

Update [Marvel] Civil War II (WEB-CBRO).cbl

---

Marvel/Master Reading Order/CBRO/[Marvel] Marvel Master Reading Order Part #13 (WEB-CBRO).cbl

Updated to match https://comicbookreadingorders.com/marvel/marvel-master-reading-order-part-13/ 2 issues moved to https://comicbookreadingorders.com/marvel/marvel-master-reading-order-part-14/

Update [Marvel] Marvel Master Reading Order Part #13 (WEB-CBRO).cbl

---

Image/Characters/Spawn/[Image] [1992-Present] Spawn (CBRO).cbl

Added updated issues
https://comicbookreadingorders.com/other/spawn-reading-order/

Update [Image] [1992-Present] Spawn (CBRO).cbl

---

Other/Star Wars/CBRO/[Marvel] 002 The Clone Wars.cbl
Other/unsorted/Adolescent Radioactive Black Belt Hamsters (original run).cbl
Other/unsorted/BOOM! Power Rangers Simplified 1a.cbl
Other/unsorted/BOOM! Power Rangers Simplified 1b.cbl
Other/unsorted/Chaos! Universe 1993 - 2002.cbl

A couple of series ID corrections buried in here

CVNameReview - /Other

---

Image/Master Reading Order/Energon Universe/[Image] [2023-Present] Energon Universe (CBH).cbl

Created a list to capture the ongoing Energon Universe (G.I. Joe, Transformers) reading order from Comic Book Herald:
https://www.comicbookherald.com/energon-universe-reading-order/

Energon Universe Reading Order

---

Marvel/Characters/Spider-Man/CBRO/Miles Morales (CBRO) with events.cbl

Updated to match updated events

Update Miles Morales (CBRO) with events.cbl

---

Marvel/Characters/Ms Marvel/[Marvel] Kamala Khan (CBRO) with events.cbl

Updated year for Rocket Raccoon & Groot https://comicvine.gamespot.com/rocket-raccoon-and-groot/4050-86989/

Update [Marvel] Kamala Khan (CBRO) with events.cbl

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #04 (WEB-CBRO).cbl

Updated to match https://comicbookreadingorders.com/marvel/marvel-master-reading-order-part-4/

Update [Marvel] Marvel Master Reading Order Part #04 (WEB-CBRO).cbl

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #03 (WEB-CBRO).cbl

Updated with Sep 2024 changes plus extra fixes
https://comicbookreadingorders.com/marvel/marvel-master-reading-order-part-3/

Update [Marvel] Marvel Master Reading Order Part #03 (WEB-CBRO).cbl

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #02 (WEB-CBRO).cbl

Corrected X-Men annual issue number
https://comicbookreadingorders.com/marvel/marvel-master-reading-order-part-2/

Correcting X-Men annual issue number

---

Marvel/Master Reading Order/CBRO/[Marvel] Marvel Master Reading Order Part #02 (WEB-CBRO).cbl

Correcting X-Men annual issue number https://comicbookreadingorders.com/marvel/marvel-master-reading-order-part-2/

Fix X-Men annual issue number

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #01 (WEB-CBRO).cbl

Updated to match https://comicbookreadingorders.com/marvel/marvel-master-reading-order-part-1/

Update [Marvel] Marvel Master Reading Order Part #01 (WEB-CBRO).cbl

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #05 (WEB-CBRO).cbl

Mostly updated the heroes reborn arc https://comicbookreadingorders.com/marvel/marvel-master-reading-order-part-5/ https://comicbookreadingorders.com/marvel/events/heroes-reborn-reading-order/

Update [Marvel] Marvel Master Reading Order Part #05 (WEB-CBRO).cbl

---

Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 12 The Heroic Age/[Marvel] 2004-2012 Part 12.1 Welcome to the New Age (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 12 The Heroic Age/[Marvel] 2004-2012 Part 12.2 Chaos War (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 12 The Heroic Age/[Marvel] 2004-2012 Part 12.3 ShadowLand (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 12 The Heroic Age/[Marvel] 2004-2012 Part 12.4 Vampires and Demons (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 12 The Heroic Age/[Marvel] 2004-2012 Part 12.5 Age of X (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 12 The Heroic Age/[Marvel] 2004-2012 Part 12.6 Spies and Soldiers (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 13 Fear Itself/[Marvel] 2004-2012 Part 13.1 The Road to Fear Itself (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 13 Fear Itself/[Marvel] 2004-2012 Part 13.2 Asgard’s Sin (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 13 Fear Itself/[Marvel] 2004-2012 Part 13.3 The Worthy (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 13 Fear Itself/[Marvel] 2004-2012 Part 13.4 Midgard’s Last Stand (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 13 Fear Itself/[Marvel] 2004-2012 Part 13.5 Shattered Heroes (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 14 Spider-Island/[Marvel] 2004-2012 Part 14.1 The Road to Spider-Island (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 14 Spider-Island/[Marvel] 2004-2012 Part 14.2 Spider-Island (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 14 Spider-Island/[Marvel] 2004-2012 Part 14.3 Spider-Island Aftermath (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 14 Spider-Island/[Marvel] 2004-2012 Part 14.4 Minimum Carnage (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 14 Spider-Island/[Marvel] 2004-2012 Part 14.5 The War of Four Cities (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 15 Avengers vs. X-Men/[Marvel] 2004-2012 Part 15.1 Some Assembly Required (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 15 Avengers vs. X-Men/[Marvel] 2004-2012 Part 15.2 Schism and Regenesis (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 15 Avengers vs. X-Men/[Marvel] 2004-2012 Part 15.3 Flight of the Phoenix (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 15 Avengers vs. X-Men/[Marvel] 2004-2012 Part 15.4 The Phoenix Five (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 15 Avengers vs. X-Men/[Marvel] 2004-2012 Part 15.5 A New Hope (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 15 Avengers vs. X-Men/[Marvel] 2004-2012 Part 15.6 End Times (MG).cbl
Marvel/Master Reading Order/Marvel Guides/README.md

Completed all pending updates for the Marvel Disassembled Era:
Jan 14 2025
Sept 11 2024
August 13 2024

Marvel Disassembled Updates from Marvel Guides

---

Marvel/Master Reading Order/Marvel Guides/Alternate Universes/Ultimate Marvel (Earth-1610)/Part 1 Brave New World/[Marvel] 2000-2015 Part 1.1 Ultimate Origins (MG).cbl
Marvel/Master Reading Order/Marvel Guides/Alternate Universes/Ultimate Marvel (Earth-1610)/Part 1 Brave New World/[Marvel] 2000-2015 Part 1.2 It's All Connected (MG).cbl
Marvel/Master Reading Order/Marvel Guides/Alternate Universes/Ultimate Marvel (Earth-1610)/Part 1 Brave New World/[Marvel] 2000-2015 Part 1.3 Gah Lak Tus (MG).cbl

Completed first three parts of the Ultimate Universe on Marvel Guides.

Marvel Guides Ultimate Universe

---

Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[1974-1983] X-Men Era Two The Uncanny X-Men (UXRO).cbl

Marvel Tales run doesn't reach issue 262, it changed names two times before this issue
https://comicvine.gamespot.com/marvel-tales-featuring-spider-man-262-nightmare-in/4000-65073/

Update [1974-1983] X-Men Era Two The Uncanny X-Men (UXRO).cbl

---

Marvel/Master Reading Order/Marvel Guides/1939-1956 Golden Age/Part 01 Timely Heroes/[Marvel] 1939-1956 Part 1.3 The War Rages On (MG).cbl
Marvel/Master Reading Order/Marvel Guides/1939-1956 Golden Age/Part 02 Super Soldiers/[Marvel] 1939-1956 Part 2.3 Winners Unite! (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 12 The Heroic Age/[Marvel] 2004-2012 Part 12.6 Spies and Soldiers (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2004-2012 Marvel Disassembled/Part 15 Avengers vs. X-Men/[Marvel] 2004-2012 Part 15.1 Some Assembly Required (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2012-2015 Marvel NOW!/Part 11 Time Runs Out/[Marvel] 2012-2015 Part 11.1 Ultimate Interlude (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2012-2015 Marvel NOW!/Part 12 Secret Wars/[Marvel] 2012-2015 Part 12.4 Warzones Part 2 (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2015-2018 ANAD Marvel/Part 06 Civil War II/[Marvel] 2015-2018 Part 6.3 The Accused and the Fallen┬á (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2015-2018 ANAD Marvel/Part 07 Civil War II Aftermath/[Marvel] 2015-2018 Part 7.4 Monsters Unleashed (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2018-2021 Fresh Start/Part 09 Dawn of X/[Marvel] 2018-2021 Part 9.2 Brave New World (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2018-2021 Fresh Start/Part 09 Dawn of X/[Marvel] 2018-2021 Part 9.3 Breaking Dawn (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2018-2021 Fresh Start/Part 11 Empyre/[Marvel] 2018-2021 Part 11.1 Incoming Threats (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2018-2021 Fresh Start/Part 11 Empyre/[Marvel] 2018-2021 Part 11.2 Outlawed (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2018-2021 Fresh Start/Part 12 X of Swords/[Marvel] 2018-2021 Part 12.1 X of Swords (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2018-2021 Fresh Start/Part 14 King in Black/[Marvel] 2018-2021 Part 14.2 King in Black (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2018-2021 Fresh Start/Part 15 Reign of X/[Marvel] 2018-2021 Part 15.1 After the Dawn Comes the Reign (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2018-2021 Fresh Start/Part 15 Reign of X/[Marvel] 2018-2021 Part 15.2 Hellfire Gala (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2018-2021 Fresh Start/Part 15 Reign of X/[Marvel] 2018-2021 Part 15.4 Trial by Fire (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2024 Timeless/Part 03 A.X.E. Judgement Day/[Marvel] 2021-2023 Part 3.1 Sleeping Giants (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2024 Timeless/Part 07 Sins of Sinister/[Marvel] 2021-2023 Part 7.1 Dawn of Essex (MG).cbl

Captain America Comics volume year was changed on CV, so went through all of Marvel Guides to check all volumes that needed updating.

Volume name and year synch with Comicvine Updates

---

Marvel/Characters/Doctor Strange/[Marvel][1988-2019] Doctor Strange (CBRO).cbl
Marvel/Characters/Spider-Man/CBRO/Miles Morales (CBRO) with events.cbl
Marvel/Characters/X-23/X-23 (CBRO).cbl
Marvel/Teams/X-Men/Age of Krakoa/Age of Krakoa - Eras Lists/[X-Men Krakoa 2.2] Judgement of X.cbl
Marvel/Teams/X-Men/Age of Krakoa/Age of Krakoa - Single List/[X-Men Krakoa] [2019-Present] The Age of Krakoa.cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 015.cbl

Updates to the 3 marvel folders, characters, teams and creator runs

volume and year updates

---

DC/Characters/Batman/[DC] Batman - Post-Crisis  [1986-2011].cbl
DC/Characters/unsorted/Blue Beetle/Blue Beetle 002 - Post Crisis.cbl
DC/Characters/unsorted/Firestorm/Firestorm 001.cbl
DC/Creator Runs/[DC] [2000-2011] Flash by Geoff Johns.cbl
DC/Events/CBRO/1991-1997 - Part 3/[DC Comics] Final Night (WEB-CBRO).cbl
DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #05 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] DC Master Reading Order Part #01 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] DC Master Reading Order Part #02 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] DC Master Reading Order Part #05 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] New 52 Reading Order- New Part #2 (WEB-CBRO).cbl
DC/Master Reading Order/Marvel Guides/2011-2016 New 52/Part 2 Edge of Darkness/[DC] 2011-2016 Part 2.3 A Wild Storm Approaches.cbl
DC/Teams/unsorted/Justice League/Justice League 005 (2006).cbl

Start year and name checks across DC folders.  Performed by script, then hand checked against CV website to confirm.  Should be a clean merge.

CV Year & Name Updates - /DC/

---

Other/unsorted/Chaos! Universe 1993 - 2002.cbl
Other/unsorted/Dynamite/Dynamite Army of Darkness Reboot.cbl

Scripted, then hand checked changes against CV.

CV Name & Year Updates - Everything that isn't Marvel & DC

---

Boom/Power Rangers/BOOM! Power Rangers Simplified 1a.cbl
Boom/Power Rangers/BOOM! Power Rangers Simplified 1b.cbl
Dark Horse/Characters/Hellboy/[Dark Horse] Hellboy (Mignolaverse) TPB Reading Order.cbl
IDW/Characters/Transformers/[IDW] [2005-2017] Transformers (CBRO).cbl
Other/Star Wars/Unknown/Master Reading Order (Unsorted)/Legacy (Dark Horse)/[Dark Horse Comics] 007 - Legacy Era.cbl
Other/unsorted/Chaos! Universe 1993 - 2002.cbl
Other/unsorted/Dynamite/Dynamite Army of Darkness Reboot.cbl

Updated volume names and years for all the other publisher folders.

Volume name and year updates

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel NOW!- Marvel NOW! Part #2 (WEB-CBRO).cbl

Replaced secret wars, too TPB with issue

Secret wars, too

---

Marvel/Characters/Wolverine/Wolverine NO Events (CBRO).cbl
Marvel/Characters/Wolverine/Wolverine with Events (CBRO).cbl

Added 2 CBLs for CBRO Wolverine to Marvel/Characters

Wolverine added

---

Marvel/Events/LoCG/[2012] Avengers vs. X-Men (Marvel Comics)(LoCG).cbl

Fix to the Avengers vs. X-Men LoCG list, replaced Marvel Point One with Point One.

Marvel Point One Fix

---

Marvel/Events/LoCG Community/README.md
Marvel/Events/LoCG Community/[2022-2023] X-Men - Destiny of X (Marvel)(LoCG).cbl

Added Destiny of X list submitted by a discord user, and created the community lists section. We can re-work the file structure if you have different thoughts.

Added LoCG Communitry List section and first list

---

Marvel/Master Reading Order/Marvel Guides/1970-1984 Bronze Age/Part 03 Ever Expanding/[Marvel] 1970-1984 Part 3.1 Step Into The Spotlight (MG).cbl
Marvel/Master Reading Order/Marvel Guides/1970-1984 Bronze Age/Part 03 Ever Expanding/[Marvel] 1970-1984 Part 3.2 Ghosts and Devils (MG).cbl
Marvel/Master Reading Order/Marvel Guides/1970-1984 Bronze Age/Part 03 Ever Expanding/[Marvel] 1970-1984 Part 3.3 Villains and Champions (MG).cbl
Marvel/Master Reading Order/Marvel Guides/README.md

April Bronze Age Update

---

Marvel/Characters/Magik/[Marvel] Magik (WEB-CBRO)

https://comicbookreadingorders.com/marvel/characters/magik-reading-order/

Create [Marvel] Magik (WEB-CBRO)

---

Dark Horse/Characters/Black Hammer/Black Hammer.cbl
Dark Horse/Characters/Black Hammer/README.md

Resubmission fixing a readme layout problem.  New list.

New Black Hammer list

---

Marvel/Master Reading Order/CMRO/Main/[Marvel] CMRO Main Reading Order-Part 03.cbl

fix captain america issues

---

Marvel/Events/Official/[Marvel] (2013) Battle of The Atom (Official).cbl

Official Marvel Reading List - https://www.marvel.com/comics/guides/136/xmen_battle_of_the_atom_complete_event

[Marvel] [2013] Battle of The Atom (Official)

---

Marvel/Master Reading Order/Marvel Guides/2015-2018 ANAD Marvel/Part 06 Civil War II/[Marvel] 2015-2018 Part 6.3 The Accused and the Fallen (MG).cbl

It made a basic print to stdout whinge about encoding, so I can't imagine it's healthy for all app consumers!

Fixing a strange character in filename

---

DC/Master Reading Order/CBRO - With Events/[DC Comics] DC Master Reading Order Part #02 (WEB-CBRO).cbl
DC/Master Reading Order/CBRO/[DC Comics] DC Master Reading Order Part #02 (WEB-CBRO).cbl

Issue 1 ID was the TPB and caused a crash in Mylar

Fix CV issue ID for Batman: The Cult

---

DC/Teams/unsorted/Legion of Super-Heroes/Legion 004 - (Post Zero Hour).cbl

Most of the issue is LSH based and it's fairly important to context for the issues in the list either side!

Added missing Superboy issue for multi-part story

---

DC/Teams/unsorted/Legion of Super-Heroes/Legion 006 - (New 52).cbl

That has to the the worst diff I've ever seen git do ...
2 changes:
Num Issues bumped to 53
Legion of Super-Heroes #17 added (line 126)

Added missing LSH issue to Legion 006
