Other/Star Wars (Marvel).cbl

I've added 22 books from High Republic, same as on https://comicbookreadingorders.com/other/star-wars-marvel-reading-order/.
There's something not quite right with diff in GitHub - nothing was changed aside from adding top 22 new entries.

Adds High Republic books to Star Wars list

---

DC/Master Reading Order/CBRO/[DC Comics] DC Master Reading Order Part #02 (WEB-CBRO).cbl

"Firestorm, the Nuclear Man" was renamed to just "Firestorm" for issues 93-100.

Update [DC Comics] DC Master Reading Order Part #02 (WEB-CBRO).cbl

---

DC/Master Reading Order/CBRO/[DC Comics] DC Master Reading Order Part #02 (WEB-CBRO).cbl

The recent change to firestorm volume name was part of the fix, but the series number and the year were also wrong. Fixing those issues with this commit.

Firestorm fix

---

Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[2003-2006] X-Men Era Thirteen House of X, House of M (UXRO).cbl
Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[2008-2009] X-Men Era Fifteen Manifest Destiny (UXRO).cbl

Excalibur #11 was in the list twice.  The first listing was the wrong volume.  That was changed to the correct volume and the second listing was removed.  Looking at the site, https://ultimatexmenreadingorder.com/x-men-era-thirteen-house-of-x-house-of-m-2003-2006/ it is listed to read half at one point in the list and the second half later in the list.  So per our discord discussion, I just selected the first issue.
Also removed TPB on Utopia

Fix for Excalibur volume and duplicate

---

Dark Horse/Characters/Hellboy/[Dark Horse] Hellboy (Mignolaverse) TPB Reading Order.cbl

Updated as per the newer version (Oct 2023) of the Hellboy reading list from here: http://www.multiversitycomics.com/annotations/hellboy-reading-order-2023/
A couple of issue ordering fixes, some consolidation (B.P.R.D. 1957), and additions, including the just-released Panya TPB.

Updated to Hellboy Oct 2023 Reading Order

---

Other/unsorted/Adolescent Radioactive Black Belt Hamsters (original run).cbl

Added all existing comics that are part of the ARBBH continuity from Eclipse and Express Publications.  Source: ComicVine as this series just spans multiple titles but is a straight line.

Adolescent Radioactive Black Belt Hamsters 1st run

---

DC/Characters/Batman/Batman - Modern Age/[DC] Batman Modern Age - Part 03 Bat-Family Year One [1980-2010].cbl

This list was originally based on one of TPBs (https://docs.google.com/spreadsheets/d/1p1Po1qYZajBMy9sSee8dJt2EoACT43sbNukdlVb7z9w/edit#gid=377939861), and the TPB for Batman: Irresistible contained the Hourman comic at the end.  The reason for its inclusion in that trade, however, was because of the common artist.  It doesn't include Batman, has no relevance to his world, and isn't even that useful as a standalone story as it's the beginning of a multipart.  Ironically, the NEXT issue in the Hourman series features a Batman of many centuries hence, but even that wouldn't sit well in this reading list.  I don't think this issue belongs here.

Remove Non-Batman Issue from Reading List

---

Other/unsorted/Chaos! Universe 1993 - 2002.cbl
Other/unsorted/Dynamite/Dynamite Army of Darkness (First Continuity).cbl
Other/unsorted/Dynamite/Dynamite Army of Darkness Reboot.cbl
Other/unsorted/Space Goat Evil Dead 2.cbl

This spans 2004-2016 there's some overlap with the second continuity release year wise but none story-related. There's a good amount of crossover goodness. I did include 1 issue without Ash which takes place simultaneously with one of the Marvel Zombie crossovers and helps inform the events you'd just read. I kept that in release order as it really is more effective from a story standpoint that way. Next up is AoD Dynamite reboot continuity and then the Space Goat Evil Dead 2 books

Army of darkness/Evil Dead 2 (3 seperate PRs rolled into one)

---

Marvel/Events/Official/[Marvel] (2020-09) X of Swords (Official).cbl
Marvel/Events/Official/[Marvel] (2021-06) Hellfire Gala (Official).cbl
Marvel/Events/Official/[Marvel] (2022-08) AXE Judgment Day (Official).cbl
Marvel/Master Reading Order/Marvel Guides/2018-2021 Fresh Start/Part 09 Dawn of X/[Marvel] 2018-2021 Part 9.2 Brave New World (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2018-2021 Fresh Start/Part 12 X of Swords/[Marvel] 2018-2021 Part 12.1 X of Swords (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2018-2021 Fresh Start/Part 15 Reign of X/[Marvel] 2018-2021 Part 15.1 After the Dawn Comes the Reign (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2018-2021 Fresh Start/Part 15 Reign of X/[Marvel] 2018-2021 Part 15.2 Hellfire Gala (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2018-2021 Fresh Start/Part 15 Reign of X/[Marvel] 2018-2021 Part 15.4 Trial by Fire (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 02 Destiny of X/[Marvel] 2021-2023 Part 2.2 Secret Pasts, Sinister Futures (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 02 Destiny of X/[Marvel] 2021-2023 Part 2.3 Hellfire and Brimstone (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 03 A.X.E. Judgement Day/[Marvel] 2021-2023 Part 3.2 Rush to Judgement (MG).cbl

Some lists had 2019 as the start year when it should be 2020. This was causing issues for CBL import in Komga. Series in question: https://comicvine.gamespot.com/x-force/4050-122668/

Fixed X-Force 2020 series start year

---

Marvel/Master Reading Order/Marvel Guides/2012-2015 Marvel NOW!/Part 01 Now or Never/[Marvel] 2012-2015 Part 1.1 Unity - Division (MG).cbl

Closes #164 
The issue says 2013,  but Comic Vine calls it 2012 as it started in December of 2012 (so 2012 just barely).

Uncanny Avengers was mapped to the wrong volume

---

Image/Master Reading Order/[Image] [2010-2015] Skullkickers (Community-contributed).cbl

Added a reading order for the Skullkickers series by Image comics, deemed it worth, since CV and Metron split the issues 19-23 off because they are titled weirdly by Image (e. g. Skullkickers #23: Dark Skullkickers Dark #1)...
Imports fine on my test sets.

Skullkickers Reading order (Image, 2010-2015)

---

Marvel/Events/unsorted/[Marvel] [2024] Symbiosis Necrosis (Community-Contributed).cbl

Added Event Reading List for Symbiosis Necrosis by Marvel. Created based on the titles of the issues, cross-verified with [Marvel's announcement](https://www.marvel.com/articles/comics/symbiosis-necrosis-venom-carnage-crossover-eddie-dylan-brock-cletus-kasady). Placed the file in unsorted as I 'hand-crafted' it.
Import verified on my test sets.

Marvel - Symbiosis Necrosis added

---

Other/unsorted/Mirage TMNT vol 1 (Laird canon) reading list.cbl

TMNT has a confusing and fractured history, even prior to IDW. Peter Laird has gone on record to say he only considers the stories by him and Eastman to be canon from the original volume 1 and Tales volume 1. I've compiled this into a chronological order story-wise with a deviation of #24-26 they are referenced in the Laird/Eastman books after so it must be canon even by his standard.

Added TMNT Laird Canon Volume 1

---

DC/Characters/Batman/Batman - Modern Age/[DC] Batman Modern Age - Part 15 Batman Reborn [1989-2012].cbl

I believe the second set of Gotham City Sirens issues on this CBL has the volume year for [the collected editions from 2014](https://comicvine.gamespot.com/gotham-city-sirens/4050-77687/) rather than [the individual issues from 2009](https://comicvine.gamespot.com/gotham-city-sirens/4050-26891/).

correct volume year for gotham city sirens

---

Marvel/Events/CBRO/2005-2009 - Part 8/[Marvel] Civil War (WEB-CBRO).cbl
Marvel/Events/CBRO/2011-2012 - Part 10/[Marvel] Avengers vs. X-Men (WEB-CBRO).cbl
Marvel/Events/CBRO/2022-2023 - Part 13/[Marvel] Dark Web (WEB-CBRO).cbl
Marvel/Events/CBRO/[Marvel] Jonathan Hickman's Marvel (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #01 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #03 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #04 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #06 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #08 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #10 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #11 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #12 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #13 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order- A Fresh Start (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order- Marvel Legacy (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO/[Marvel] Marvel Master Reading Order Part #01 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO/[Marvel] Marvel Master Reading Order Part #03 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO/[Marvel] Marvel Master Reading Order Part #06 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO/[Marvel] Marvel Master Reading Order Part #11 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO/[Marvel] Marvel Master Reading Order Part #12 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO/[Marvel] Marvel Master Reading Order Part #13 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO/[Marvel] Marvel Master Reading Order- A Fresh Start (WEB-CBRO).cbl

Some records have correct CV id, but different volume year or volume name, other records have correct name/year, but invalid CV id.
`Marvel/Events/CBRO/2005-2009 - Part 8/[Marvel] Civil War (WEB-CBRO).cbl`
`Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #08 (WEB-CBRO).cbl`
Series [Civil War](https://comicvine.gamespot.com/civil-war/4050-18023/), volume year was higher than the issue year, fixed to be the same as CV.
`Marvel/Events/CBRO/2011-2012 - Part 10/[Marvel] Avengers vs. X-Men (WEB-CBRO).cbl`
`Marvel/Events/CBRO/[Marvel] Jonathan Hickman's Marvel (WEB-CBRO).cbl`
`Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #10 (WEB-CBRO).cbl`
Series [Avengers Vs …

[CBRO] Fix errors and inconsistencies for CBRO master reading order and events

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #06 (WEB-CBRO).cbl

From event: https://comicbookreadingorders.com/marvel/events/maximum-security-reading-order/
Vol 4 is https://comicvine.gamespot.com/captain-marvel/4050-18296/
After it leads to this in part 6 https://comicbookreadingorders.com/marvel/marvel-master-reading-order-part-6/

Fixed Captain Marvel volume in Marvel CBRO with events part 6

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #09 (WEB-CBRO).cbl

There is two events in https://comicbookreadingorders.com/marvel/marvel-master-reading-order-part-9/
https://comicbookreadingorders.com/marvel/events/heroic-age-reading-order/
https://comicbookreadingorders.com/marvel/events/curse-of-the-mutants-reading-order/
They both include Death of Dracula (2010)
Removed 2011 volume of it from CBL, because it added by mistake
Left earlier entry

Fixed Death of Dracula wrong entry in Marvel CBRO with events part 9

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #10 (WEB-CBRO).cbl

First we have this: https://comicbookreadingorders.com/marvel/events/spider-verse-reading-order/
Then we have this: https://comicbookreadingorders.com/marvel/events/secret-wars-2015-reading-order/
First one meant to be: https://comicvine.gamespot.com/spider-verse/4050-78047/
Changed as it should be

Adjusted spider-verse volumes in CBRO part 10 with events

---

Marvel/Teams/X-Men/Ultimate X-Men Reading Order/[2014-2015] X-Men Era Twenty-One Time Runs Out (UXRO).cbl

As with many Marvel events, Black Vortex had an Alpha and Omega issue at the start and end.  These were missing from the list.

Added missing Black Vortex bookend issues

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #10 (WEB-CBRO).cbl

Was looking at TPB here: https://comicvine.gamespot.com/secret-wars-too/4050-93678/
I changed it to actual issue: https://comicvine.gamespot.com/secret-wars-too/4050-86122/
Honestly no idea what here at the end meant to be, but I'm kinda sure issue and not TPB: https://comicbookreadingorders.com/marvel/events/secret-wars-2015-reading-order/

Fixed Secret Wars, Too from tpb to issue in part 10 cbro events

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #08 (WEB-CBRO).cbl

`The New Avengers: Illuminati` removed because planet hulk and civil war happens at same time
https://comicbookreadingorders.com/marvel/events/planet-hulk-reading-order/
https://comicbookreadingorders.com/marvel/events/civil-war-reading-order/
`Ms. Marvel 10` have place inside civil war and no need to check later entry after civil war in main order
`Civil War: Initiative` removed The Initiative entry, it already included in civil war
https://comicbookreadingorders.com/marvel/events/the-initiative-reading-order/
https://comicbookreadingorders.com/marvel/events/civil-war-reading-order/
All X-Men stuff removal related to it being included into `X-Men: Endangered Species`
https://comicbookreadingorders.com/marvel/events/x-men-endangered-species-reading-order/

Fixed duplicates in CBRO with events part 8

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] All-New, All Different Marvel- All-New, All-Different Marvel Part #1 (WEB-CBRO).cbl

There is this: https://comicvine.gamespot.com/deadpool-the-mercs-for-money/4050-87793/
And this: https://comicvine.gamespot.com/deadpool-the-mercs-for-money/4050-92360/
First 5 issues already present in CBL, next 5 had incorrect matching to first one still, but shall belong to second one
Issue 6 match is correct tho

Adjusted deadpool mercs for money in cbro with events

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #09 (WEB-CBRO).cbl

replaced issues from World War Hulk event with issues from Utopia event
The issues from the event World War Hulk were in the location that should have contained the issues from the event Utopia.

fixed World War Hulk issue in part 9

---

Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel Master Reading Order Part #10 (WEB-CBRO).cbl
Marvel/Master Reading Order/CBRO - With Events/[Marvel] Marvel NOW!- Marvel NOW! Part #2 (WEB-CBRO).cbl

In https://comicbookreadingorders.com/marvel/marvel-master-reading-order-part-10/
we have link to now 
here in part 2 we have ant-man vol 2 2015
Fixed wrong link to 2020 volume

Fixed Ant-Man wrong volumes in Marvel CBRO with events part 10

---

Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 01 Once and Future/[Marvel] 2021-2023 Part 1.1 For All Time (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 01 Once and Future/[Marvel] 2021-2023 Part 1.2 Heroes of the People (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 01 Once and Future/[Marvel] 2021-2023 Part 1.3 Reckoning War (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 01 Once and Future/[Marvel] 2021-2023 Part 1.5 Fight for the Future (MG).cbl
Marvel/Master Reading Order/Marvel Guides/2021-2023 Timeless/Part 01 Once and Future/[Marvel] 2021-2023 Part 1.6 Across the Multiverse (MG).cbl

There's been some reshuffling since these lists were first created, this commit aligns the lists with the current content of the Marvel Guides site.

Marvel Guides: update Timeless Part 1 lists to match site

---

Marvel/Teams/Fantastic Four/[Marvel] [Post-Civil War - Secret Wars] Fantastic Four (Comic Book Herald).cbl

Add a reading list of Fantastic Four between the Civil War and Secret Wars events as laid out by ComicBookHerald here: https://www.comicbookherald.com/fantastic-four-reading-order/ (Most of Part V + Part VI + Part VII)

Add new Fantastic Four list from ComicBookHerald

---

DC/Characters/unsorted/Batgirl/Batgirl 001 (Pre-Crisis).cbl
DC/Characters/unsorted/Batgirl/Batgirl 002 (Post-Crisis).cbl
DC/Characters/unsorted/Batgirl/Batgirl 003 (New52_Rebirth).cbl
DC/Characters/unsorted/Batman Beyond/Batman Beyond 001.cbl
DC/Characters/unsorted/Batwoman/Batwoman.cbl
DC/Characters/unsorted/Birds of Prey/Birds of Prey 001 (Post-Crisis).cbl
DC/Characters/unsorted/Birds of Prey/Birds of Prey 002 (New52_Rebirth).cbl
DC/Characters/unsorted/Black Lightning/Black Lightning.cbl
DC/Characters/unsorted/Blue Beetle/Blue Beetle 001 - Pre-Crisis.cbl
DC/Characters/unsorted/Blue Beetle/Blue Beetle 002 - Post Crisis.cbl
DC/Characters/unsorted/Blue Beetle/Blue Beetle 003 - New52_Rebirth.cbl

- Have ignored the Batman folder.  Not short of Batman lists, so focussing effort elsewhere!
- The two TPBs at the start of Batgirl don't seem to exist.  Maybe they are custom compilations?  Have substituted what I think are appropriate omnibus collections.
- Completed the end of the trailing Batman Beyond series and added the two next series linked on ComicVine
- Could not find a TPB for the named Black Lightning / Blue Devil collection, but there are 4 issues titled that in the DC Presents series
- Expanded pre-crisis Blue Beetle v1 + TPBs for crisis events

CV ID Mapping - DC/Characters/unsorted/B

---

Marvel/Teams/unsorted/X-Men/Alpha Flight/Alpha Flight.cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 001 (Original Team).cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 002 (New X-Men).cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 003.cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 004 (Blue - Gold).cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 005.cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 006.cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 007.cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 008 (Morrison Era).cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 009 (X-Men Reload).cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 010 (Decimation).cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 011 (Messiah Complex).cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 012.cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 013 - (Regenesis).cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 014 - (Marvel NOW!).cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 015.cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 016 (All New, All Different).cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 017 - (Resurrection).cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 018.cbl
Marvel/Teams/unsorted/X-Men/X-Men - Part 019 - (Hickman Era).cbl

Review notes:
- There are two commits.  The first was just to clear out some extraneous data from all lists in order to make the second diff clearer (i.e. should be 95% just swapping an <Id> for a <Database> element with no other metadata changes.
- Name changes mostly either ampersand differences or that period where Marvel's annuals weren't named "Annual" but with just the year (95-2001ish).  Some are the usual indicia obsession.
- Most date changes are subtle movements because of end of year cover/release year differences.
- Uncanny X-Men Annual has lots of name/date changes because of the way it is captured in CV (initially as "X-Men Annual", then an "Uncanny X-Men Annual" run from #16 starting in 1992).
- I've removed one issue where I literally could not find a Wolverine #0
- I …

CV ID Mapping - Marvel/Teams/unsorted/X-Men

---

Marvel/Characters/unsorted/Adam Warlock/Adam Warlock.cbl

Warlock #8 came out in Oct 1973. Warlock #9 came out in Oct 1975. The storyline from #8 was finished in The Incredible Hulk 176-178. Next Jim Starlin began writing Warlock stories in Strange Tales 178-181. Strange Tales 181 came out in Aug of 1975. After that Warlock #9 was advertised as a Premiere Issue and came out in Oct 1975.
This pull request is to move those Hulk and Strange Tales issues into the correct chronological AND story order between Warlock #8 and #9.

Update Adam Warlock.cbl

---

Marvel/Events/CBH/[Marvel] [2014-2015] Death of Wolverine (CBH).cbl

Enhanced .cbl of this pre-existing event including: 2014 Wolverine ongoing, which is the catalyst of the entire event, and the 2015 "Wolverines" series which serves as the epilogue to the event. 
https://www.comicbookherald.com/the-complete-marvel-reading-order-guide/death-of-wolverine-reading-order/

Enhanced Death of Wolverine Reading List (CBH)

---

Marvel/Events/CBH/[Marvel] [2015-2016] Secret Wars (Simplified) (CBH).cbl

A more streamlined reading order for secret wars, omitting a lot of unnecessary/optional tie-ins that may scare off newer readers (like myself) looking to read the event in its entirety. This was mainly curated with the help of CBH, but perfecting the order as well as the chronology was somewhat of a personal endeavor.
https://www.comicbookherald.com/the-complete-marvel-reading-order-guide/secret-wars-reading-order/
https://www.comicbookherald.com/the-complete-marvel-reading-order-guide/secret-wars-reading-order/battleworld-warzone-last-days-checklists/

[Marvel] [2015-2016] Secret Wars (Simplified) (CBH)
